### PR TITLE
Separate into library

### PR DESCRIPTION
**Pull request by jD91mZM2**
I was thinking we should make it easier to make new window managers, so I started some tiny bit of work on making orbital into a library.
What do you think?

(I'll work more on this later)

### CODE REVIEW

**Comment by jackpot51** [comment]
This is a good idea. I will take a deeper look into this

**Comment by jD91mZM2** [comment]
It works now, although I'm unsure whether or not the current interface is high level enough or if more components should be moved.

**Comment by jD91mZM2** [comment]
Where is the code for *actually* drawing the window contents? Where is it getting it from? I don't see any code for that... Neither do I see any usage of `read`/`map`... are those related? Is this something that should be abstracted away in the library?

**Comment by jD91mZM2** [comment]
Unforeseen pitfall: `scheme_event` can delay packets if the window is async. I initially wanted the library to not know anything about the windows at all, but rather leave all window events to callbacks. Maybe we just revert the latest commit, although that would leave the library harder to use. Any suggestions?

**Comment by jD91mZM2** [comment]
Solved it, perhaps non-optimally, with a `should_delay` callback thing. What's next for this PR is to figure out how to make the `read`/`map`/whatever functions safe...er

**Comment by jD91mZM2** [comment]
This works, but it sort of looks slower. I don't know if that's actually the case though, because I don't see why it would. Basically I avoided the `ptr::write` call and mutated an instance gained from `slice::from_raw_parts_mut` instead.

**Comment by jD91mZM2** [comment]
Sorry for being slow, I just set up a new distribution on my computer.

There are still a few issues I have to look at:
 - Lag. Every once in a while it doesn't receive display events for a few seconds. Interestingly enough, it's still getting scheme events. So the code isn't slow or anything like that.
 - Resizing causes render issues. I'm probably missing some redraw call somewhere.

**Comment by jD91mZM2** [comment]
Rebased on top of the latest changes and tested. Seems to work fine :)

**Comment by jD91mZM2** [comment]
LOL! Seems like I simply returned the wrong value from `read`, and that caused an enormous amount of lag. Still a bit laggy, so I'll have to do some more debugging. But this fixed most of the issues heh

**Comment by jD91mZM2** [comment]
Seems like the last bugs I found existed even before this PR. So I think it's ready to be merged :)

(By the way, this did *not* take me 6 hours to find out. I had to leave the computer for most of that time :stuck_out_tongue:)

**Comment by jD91mZM2** [comment]
This got rid of the last piece of lag. Turns out I accidentally inverted async/sync lol

**Pull request merged**
